# Generated by Django 5.2.5 on 2025-10-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_language_book_bookinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_copies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
